---
abstract: 'simple spreadsheet worker'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-Wright
no_index:
  directory:
    - inc
    - t
recommends:
  Archive::Zip: 0
  DateTime: 0
  HTML::HTML5::Writer: 0
  JSON: 0
  Spreadsheet::WriteExcel: 0
  XML::LibXML: 0
requires:
  Encode: 0
  IO::File: 0
  Text::CSV: 0
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Spreadsheet-Wright
  homepage: http://search.cpan.org/dist/Spreadsheet-Wright/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/Spreadsheet-Wright/
version: 0.102
